version: "3"

services:
  db:
    image: postgres:16.1
    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - service_db:/var/lib/postgresql/data

volumes:
  service_db:
